# Settings
baseurl = "https://sethmcbean.com/"
languageCode = "en-us"
title = "Seth McBean"
theme = "autophugo"
#googleAnalytics = ""
disableKinds = ["taxonomy", "taxonomyTerm"]


[Author]
    name = "Seth McBean"
#    email = "kc0bfv@gmail.com"

[params]
    # Meta
    description = "Seth McBean - Portfolio"
    keywords = "bewerbungsfoto, sport portrait, portrait, fotograf, beauty, commercial fotograf, commercial photographer"
    #msvalidate = ""
    googlesiteverification = "oxbYgy5eNv8o87NpRlqLo3ywsXSsNsfU2w5n57DeL4g"
    thumb_width = 600
    thumb_quality = 70
    full_width = 2048
    full_quality = 90
    column_count = 3
    filename_as_phototitle = false
    images_downloadable = false

    #[params.favicon]
    #href = "favicon-96x96.png"
    #type = "image/png"
    #sizes = "16x16, 32x32, 96x96"

    # Headerbar links
    # Do not put here too many links,
    # it will break mobile appearance

    [[params.header.links]]
    name = "info"
    url = "#footer"
    icon = "fa-bars"    
    
    # Footer panel
    
    [params.footer.paragraph]
    headline = "about me"
    text = "\tPhotography is not my passion.\n \nMy mission is to elevate the image of businesses, organizations, and individuals in the eyes of an ever-changing marketplace, empowering people with the visual tools necessary to resonate and make a lasting mark. \n \n\tStill images move me.\n \nWhile I perfectly understand the allure of motion pictures, I work primarily in still media. I believe more timeless depth, nuance, and intrigue can be communicated through a singular well-crafted frame than can be conveyed via haphazardly produced video. Rather than adopting a Jack-of-all-trades hybrid approach, I take great satisfaction in embracing my role as an integral member of a creative production team.\n \n\tI craft visual tools.\n\nI hold a steadfast belief that photographs transcend mere aesthetic value; they are tools with the potential to be profoundly effective. To me, the real value of a photograph lies not only in visual appeal, but in its capacity to achieve a desired effect. Each image we create is crafted with this philosophy in mind, a belief that guides my every frame. If the thought of harnessing photography as a strategic tool resonates with you, then let's join perspectives and bring to life something both beautiful and impactful.\n \n My name is Seth McBean and I am a commercial photographer originally from the Bronx, NYC."
  
    [params.footer.social]
    headline = "Connect with me"

    [[params.footer.social.links]]
    label = "Pic-Time"
    url = "https://sethmcbean.pic-time.com/portfolio"
    icon = "fa-camera-retro"

    [[params.footer.social.links]]
    label = "Github"
    url = "https://github.com/beansh"
    icon = "fa-github"

    # [[params.footer.social.links]]
    # label = "LinkedIn"
    # url = "#"
    # icon = "fa-linkedin"
    
    # Contact form
    
    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'realEmail' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    
    [params.footer.contact]
    hide = false # Set this to true if you don't want to have a contact form on your site
    #realEmail = ""
    formspark_form_id = "747f8RWB"
    botpoison_public_key = "pk_bc82d1ca-d96f-454d-890e-325acf5d4dec"
    headline = "Get in touch"
    buttonText = "Send"
    resetText = "Reset"
    
    # 'warning' defines error messages for invalid inputs
    [params.footer.contact.name]
    text = "Name *"
    warning = "Please, enter your name"

    [params.footer.contact.email]
    text = "Email *"
    warning = "Please, enter your email."

    [params.footer.contact.message]
    text = "Message *"
    warning = "Please, enter your message"
    
    # Copyright
    [params.footer.copyright]
    name = "Copyright 2023, Seth McBean. All rights reserved. All of the images on this web site may not be reproduced, edited, published, distributed, displayed, performed, copied or stored for public or private use in any other support without permission"
